import { Lead, TeamMember, User, CommunicationEvent } from './types';

export const USERS: User[] = [
  { id: 1, username: 'admin', password: 'admin123', firstName: 'Admin', lastName: 'User', avatar: 'AU', role: 'admin' },
  { id: 2, username: 'john', password: 'password', firstName: 'John', lastName: 'Doe', avatar: 'JD', role: 'sales' },
  { id: 3, username: 'jane', password: 'password', firstName: 'Jane', lastName: 'Smith', avatar: 'JS', role: 'sales' },
  { id: 4, username: 'mike', password: 'password', firstName: 'Mike', lastName: 'Johnson', avatar: 'MJ', role: 'dealers' },
];

export const TEAM_MEMBERS: { sales: TeamMember[], dealers: TeamMember[], admin: TeamMember[] } = {
  sales: [
    { id: 2, username: 'john', firstName: 'John', lastName: 'Doe', avatar: 'JD', role: 'sales', email: 'john@roof.com', phone: '555-1234', stats: { leads: 50, contacted: 40, converted: 10 } },
    { id: 3, username: 'jane', firstName: 'Jane', lastName: 'Smith', avatar: 'JS', role: 'sales', email: 'jane@roof.com', phone: '555-5678', stats: { leads: 62, contacted: 55, converted: 15 } },
  ],
  dealers: [
    { id: 4, username: 'mike', firstName: 'Mike', lastName: 'Johnson', avatar: 'MJ', role: 'dealers', email: 'mike@roof.com', phone: '555-9876', stats: { leads: 30, contacted: 25, converted: 8 } },
  ],
  admin: [
    { id: 1, username: 'admin', firstName: 'Admin', lastName: 'User', avatar: 'AU', role: 'admin', email: 'admin@roof.com', phone: '555-ADMIN', stats: { leads: 0, contacted: 0, converted: 0 } },
  ]
};

export const LEADS: Lead[] = [
  {
    id: 1,
    listingLink: 'http://example.com/1',
    agentName: 'Alice Johnson',
    agentEmail: 'alice@realestate.com',
    agentPhone: '555-1111',
    address: '123 Oak St',
    city: 'Springfield',
    zipCode: '12345',
    homeType: 'Single Family',
    homeValue: '350000',
    roofFlag: 'Roof Permit',
    lastSoldDate: '2018-05-20',
    permits: 'None',
    status: 'new',
    assignedTo: 'John Doe',
    dateAdded: '2023-10-26',
    communication: { calls: 0, sms: 0, voicemails: 0, notes: [] },
  },
  {
    id: 2,
    listingLink: 'http://example.com/2',
    agentName: 'Bob Williams',
    agentEmail: 'bob@realestate.com',
    agentPhone: '555-2222',
    address: '456 Maple Ave',
    city: 'Shelbyville',
    zipCode: '54321',
    homeType: 'Townhouse',
    homeValue: '280000',
    roofFlag: '',
    lastSoldDate: '2020-01-15',
    permits: 'Roofing (2015)',
    status: 'contacted',
    assignedTo: 'Jane Smith',
    dateAdded: '2023-10-25',
    communication: { calls: 2, sms: 3, voicemails: 1, notes: [{ date: '2023-10-26', text: 'Called, left voicemail.', author: 'Jane Smith' }] },
  },
  {
    id: 3,
    listingLink: 'http://example.com/3',
    agentName: 'Charlie Brown',
    agentEmail: 'charlie@realestate.com',
    agentPhone: '555-3333',
    address: '789 Pine Ln',
    city: 'Springfield',
    zipCode: '12345',
    homeType: 'Single Family',
    homeValue: '420000',
    roofFlag: 'May Need Roof',
    lastSoldDate: '2015-11-10',
    permits: 'Electrical (2019)',
    status: 'appointment',
    assignedTo: 'Mike Johnson',
    dateAdded: '2023-10-24',
    communication: { calls: 5, sms: 2, voicemails: 0, notes: [{ date: '2023-10-25', text: 'Spoke with agent, interested in a quote.', author: 'John Doe' }] },
  },
  {
    id: 4,
    listingLink: 'http://example.com/4',
    agentName: 'Diana Prince',
    agentEmail: 'diana@realestate.com',
    agentPhone: '555-4444',
    address: '101 Elm St',
    city: 'Capital City',
    zipCode: '67890',
    homeType: 'Condo',
    homeValue: '210000',
    roofFlag: '',
    lastSoldDate: '2022-03-01',
    permits: 'None',
    status: 'appointment',
    assignedTo: 'Mike Johnson',
    dateAdded: '2023-10-22',
    communication: { calls: 8, sms: 5, voicemails: 1, notes: [{ date: '2023-10-23', text: 'Signed contract.', author: 'Jane Smith' }] },
  },
  {
    id: 5,
    listingLink: 'http://example.com/5',
    agentName: 'Eva Green',
    agentEmail: 'eva@realestate.com',
    agentPhone: '555-5555',
    address: '202 Birch Rd',
    city: 'Oak Park',
    zipCode: '98765',
    homeType: 'Duplex',
    homeValue: '310000',
    roofFlag: '',
    lastSoldDate: '2021-08-12',
    permits: 'None',
    status: 'follow-up needed',
    assignedTo: 'John Doe',
    dateAdded: '2023-10-28',
    communication: { calls: 1, sms: 1, voicemails: 0, notes: [{ date: '2023-10-28', text: 'Initial contact made, needs follow-up next week.', author: 'John Doe' }] },
  },
];


export const COMMUNICATION_EVENTS: CommunicationEvent[] = [
    { id: 1, leadId: 2, type: 'call', date: '2023-11-05', time: '10:00' },
    { id: 2, leadId: 3, type: 'sms', date: '2023-11-05', time: '14:30' },
    { id: 3, leadId: 4, type: 'voicemail', date: '2023-11-06', time: '09:15' },
    { id: 4, leadId: 1, type: 'call', date: '2023-11-08', time: '11:00' },
];